update gcode

diff --git a/lib/config b/lib/config
--- a/lib/config
+++ b/lib/config
@@ -10,14 +10,13 @@ ___x_cmd_gcode_config(){
     param:run
 
     ___x_cmd_gcode_config _param_help_doc
-    gcode_log warn "Subcmd Not Found."
+
     return 1
 }
 
 ___x_cmd_gcode_config_which(){
     param:void
-    local O="${O:-___x_cmd_gcode_GCODE_DEFAULT}"
-    printf "%s" "$___X_CMD_ROOT/.config/x-bash/app.gitlab.config/$O"
+    printf "%s\n" "$HOME/.x-cmd/.config/x-bash/app.gitlab.config/___x_cmd_gcode_GITLAB_DEFAULT"
 }
 
 ___x_cmd_gcode_config_get(){
@@ -26,13 +25,12 @@ ___x_cmd_gcode_config_get(){
 type:
     ConfigName  =   oauth_token user git_protocol
 options:
-    --host        "host name"                               <>="gitcode.net"
+    --host        "host name"                               <>="gitlab.com"
     #1            "The name of the configuration to get"    <>:ConfigName
 '
     param:run
-    local O="${O:-___x_cmd_gcode_GCODE_DEFAULT}"
-    [ -e  "$___X_CMD_ROOT/.config/x-bash/app.gitlab.config/$O" ] || return 1
-    ___x_cmd_git_config_get "$___X_CMD_ROOT/.config/x-bash/app.gitlab.config/$O" "$host" "$1"
+    [ -e  "$HOME/.x-cmd/.config/x-bash/app.gitlab.config/___x_cmd_gcode_GITLAB_DEFAULT" ] || return 1
+    ___x_cmd_git_config_get "$HOME/.x-cmd/.config/x-bash/app.gitlab.config/___x_cmd_gcode_GITLAB_DEFAULT" "$host" "$1"
 }
 
 ___x_cmd_gcode_config_set(){
@@ -41,14 +39,14 @@ ___x_cmd_gcode_config_set(){
 type:
     ConfigName  =   oauth_token user git_protocol
 options:
-    --host    "host name"                             <>="gitcode.net"
+    --host    "host name"                             <>="gitlab.com"
     #1        "Please provide configuration key"      <>:ConfigName
     #2        "Please provide configuration val"      <>
 '
     param:run
-    local O="${O:-___x_cmd_gcode_GCODE_DEFAULT}"
-    local ___gitlab_path="$___X_CMD_ROOT/.config/x-bash/app.gitlab.config/$O"
-    [ -e  "$___gitlab_path" ] || mkdir -p "$___gitlab_path##*/"
-    ___x_cmd_git_config_set "$___gitlab_path" "$host" "$1" "$2" && return 0
-    gcode_log error "gitlab config set fail"
+    local ___gitlab_path="$HOME/.x-cmd/.config/x-bash/app.gitlab.config"
+    [ -d  "$___gitlab_path" ] || mkdir -p "$___gitlab_path"
+    ___gitlab_path="$___gitlab_path/___x_cmd_gcode_GITLAB_DEFAULT"
+    ___x_cmd_git_config_set "$___gitlab_path" "$host" "$1" "$2" && ___x_cmd_ui_tf true "set config successfully" && return 0
+    gcode_log error "gcode config set Fail"
 }
